import:
  - ~/.config/alacritty/dracula.yml

env:
  TERM: xterm-256color

window:
  decorations: none

font:
  size: 9
  normal:
    #family: Fira Code
    #style: Light
    family: Source Code Pro
    style: Regular 
  bold:
    #family: Fira Code
    #style: Medium
    family: Source Code Pro
    style: Medium
  italic:
    #family: Menlo
    family: Source Code Pro
    style: Italic

shell:
  program: /usr/bin/zsh
  args:
    - --login
