import:
  - ~/.config/alacritty/dracula.yml

env:
  TERM: xterm-256color

window:
  decorations: none

font:
  size: 9 
  normal:
    family: Hack
    style: Regular 
  bold:
    family: Hack
    style: Bold
  italic:
    family: Hack
    style: Italic

shell:
  program: /usr/bin/zsh
  args:
    - --login
