---
- name: Get GnuPG key for rvm
  command: gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

- name: Upgrade rvm version
  command: "{{ rvm_bin }} get stable"

- name: Source zsh config
  import_tasks: zsh.yaml
  when: ansible_env.SHELL == '/usr/bin/zsh'

- name: Source bash config
  import_tasks: bash.yaml
  when: ansible_env.SHELL == '/usr/bin/bash' or ansible_env.SHELL == '/bin/bash'

- name: Register existing rvmrc
  stat:
    path: "{{ rvmrc.file }}"
  register: rvmrc_old

- name: Backup existing rvmrc
  command:
    cmd: mv "{{ rvmrc.file }}" "{{ rvmrc.backup }}"
    creates: "{{ rvmrc.backup }}"
    removes: "{{ rvmrc.file }}"
  when: rvmrc_old.stat.exists and rvmrc_old.stat.islnk == False

- name: Register existing gemrc
  stat:
    path: "{{ gemrc.file }}"
  register: gemrc_file

- name: Backup existing gemrc
  command:
    cmd: mv "{{ gemrc.file }}" "{{ gemrc.backup }}"
    creates: "{{ gemrc.backup }}"
    removes: "{{ gemrc.file }}"
  when: gemrc_file.stat.exists and gemrc_file.stat.islnk == False

- name: Link config files
  become: yes
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  loop:
    - { src: "{{ rvmrc.repo }}", dest: "{{ rvmrc.file }}" }
    - { src: "{{ gemrc.repo }}", dest: "{{ gemrc.file }}" }

- name: Get openssl from rvm
  command: "{{ rvm_bin }} pkg install openssl"

- name: Install latest stable Ruby version
  command: "{{ rvm_bin }} install ruby --with-openssl-dir=$HOME/.rvm/usr"

- name: Set latest stable Ruby version to default Ruby
  command: "{{ rvm_bin }} alias create default ruby"



