---
- set_fact:
    rvm_installed: False

- name: Install rvm on Arch
  import_tasks: pacman.yaml
  when: ansible_facts['os_family']|lower == 'archlinux'

- name: Install rvm on Ubuntu Linux
  import_tasks: apt.yaml
  when: ansible_facts['os_family']|lower == 'debian'

- import_tasks: config.yaml
  when: rvm_installed
