---
- name: Clone/update AUR for IntelliJ Idea (UE) 
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/intellij-idea-ultimate-edition.git"
    dest: "{{ aur.intellij_idea_ue }}"

- name: Build IntelliJ Idea (UE) package
  ansible.builtin.command: makepkg -f
  args:
    chdir: "{{ aur.intellij_idea_ue }}"

- name: Install IntelliJ Idea (UE) using pacman
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_fileglob:
    - "{{ aur.intellij_idea_ue }}/*.zst"
