---
- import_tasks: apt.yaml
  when: ansible_facts['os_family']|lower == 'debian'

- import_tasks: pacman.yaml
  when: ansible_facts['os_family']|lower == 'archlinux'

- name: Register existing config in ~ that is not a link
  stat: path="{{ abcde.file }}"
  register: config_file

- name: Backup existing config from ~ to ./backup/
  command: mv "{{ abcde.file }}" "{{ abcde.backup_path }}" creates="{{ abcde.backup_path }}" removes="{{ abcde.file }}"
  when: config_file.stat.islnk is defined and config_file.stat.islnk == False

- name: Link config from this repositry to ~
  file:
    src: "{{ abcde.repo_path }}"
    dest: "{{ abcde.file }}"
    state: link
