---
- name: Install beets, cdrdao, flac, opus, lame and id3 + needed dependecies via pacman
  become: yes
  community.general.pacman:
    name:
      - abcde
      - cdparanoia
      - cdrdao
      - cdrtools
      - beets
      - flac
      - glyr
      - id3v2
      - inetutils
      - mp3info
      - lame
      - opus
      - opus-tools
    state: latest
    update_cache: yes

- name: Install abcde via paru
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: abcde
    use: paru
    state: present
    update_cache: yes
