---
- name: Install Python & pip via apt
  become: yes
  apt:
    pkg:
      - python3
      - python3-pip
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Install python to update-alternatives
  become: yes
  alternatives:
    name: python
    link: /usr/bin/python
    path: "/usr/bin/python3"
    priority: 1
