---
- name: "Install fonts"
  become: yes
  community.general.pacman:
    name:
      - ttf-caladea
      - ttf-carlito
      - ttf-dejavu
      - ttf-liberation
      - ttf-linux-libertine-g
      - noto-fonts
      - adobe-source-code-pro-fonts
      - adobe-source-sans-pro-fonts
      - adobe-source-serif-pro-fonts
    state: latest
    update_cache: yes

- name: "Install LibreOffice"
  become: yes
  community.general.pacman:
    name:
      - libreoffice-still
      - libreoffice-extension-texmaths
      - libreoffice-extension-writer2latex
    state: latest
    update_cache: yes

- name: "Install spelling packages"
  become: yes
  community.general.pacman:
    name:
      - hunspell-de
      - hunspell-en_gb
      - hunspell-en_us
      - hunspell-es_es
      - hunspell-fr
      - hyphen-de
      - hyphen-en
      - hyphen-es
      - hyphen-fr
      - mythes-de
      - mythes-en
      - mythes-es
      - mythes-fr
    state: latest
    update_cache: yes
