---
- import_tasks: apt.yaml
  when: ansible_facts['os_family']|lower == 'debian'

- import_tasks: pacman.yaml
  when: ansible_facts['os_family']|lower == 'archlinux'

- name: Make it the default shell
  become: yes
  user:
    name: "{{ansible_env.USER}}"
    shell: /bin/zsh

- name: Backup existing dotfile from ~ to dot/backup/
  command: mv "{{item.0}}" "{{item.1}}" creates="{{item.1}}" removes="{{item.0}}"
  loop: "{{ dest_files | zip(backup_files) | list }}"

- name: Link dotfile from dot/ to ~
  file:
    src: "{{item.0}}"
    dest: "{{item.1}}"
    state: link
    force: yes
  loop: "{{ src_files | zip(dest_files) | list }}"
