---
- name: Link spotify.list to /etc/apt/sources.list.d
  become: yes
  file:
    src: "{{ ansible_env.PWD }}/etc/apt/sources.list.d/spotify.list"
    dest: "/etc/apt/sources.list.d/spotify.list"
    state: link

- name: Get spotify key
  become: yes
  shell: curl -sS https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg

- name: Install Spotify via apt
  become: yes
  apt:
    name: spotify-client
    state: latest
    update_cache: yes
