---
- name: Get GnuPG key for spotify
  command: gpg2 --recv-keys 8FD3D9A8D3800305A9FFF259D1742AD60D811D58

- name: Install dependencies (libcurl-gnutls) via pacman
  become: yes
  community.general.pacman:
    name: libcurl-gnutls
    state: present

- name: Clone/update AUR for spotify 
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/spotify.git"
    dest: "{{ aur.spotify }}"

- name: Build spotify package
  ansible.builtin.command: makepkg -f
  args:
    chdir: "{{ aur.spotify }}"

- name: Install spotify using pacman
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_fileglob:
    - "{{ aur.spotify }}/*.zst"
