---
- name: Get GnuPG key for spotify
  command: gpg2 --recv-keys 8FD3D9A8D3800305A9FFF259D1742AD60D811D58

- name: Install dependencies (libcurl-gnutls) via pacman
  become: yes
  community.general.pacman:
    name: libcurl-gnutls
    state: present

- name: paru -S spotify
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: spotify
    use: paru
    state: present
    update_cache: yes
