---
- name: Register existing i3 config in ~/.i3/config
  stat:
    path: "{{ i3config.file }}"
  register: traditional_path

- name: Register existing i3bocks config in ~/.i3/config
  stat:
    path: "{{ i3config.file }}"
  register: traditional_path

- name: Create backup path for existing config in ./backup/i3
  file:
    path: "{{ i3config.backup_path }}"
    state: directory
  when: traditional_path.stat.exists and traditional_path.stat.islnk == False

- name: Backup existing config from ~/.i3/config to ./backup/i3/config
  command: mv "{{ i3config.file }}" "{{ i3config.backup_file }}"
  when: traditional_path.stat.exists and traditional_path.stat.islnk == False
