---
- name: Register existing config in ~/.config/i3blocks/config
  stat:
    path: "{{ i3blocks.file }}"
  register: i3blocks_path

- name: Create backup path for existing config in ./backup/config/i3blocks
  stat:
    path: "{{ i3blocks.backup_path }}"
    state: directory
  when: i3blocks_path.stat.exists and i3blocks_path.stat.islnk == False

- name: Backup existing config from ~/.config/i3blocks/config to ./backup/config/i3blocks/config
  command: mv "{{ i3blocks.file }}" "{{ i3blocks.backup_path }}"
  when: i3blocks_path.stat.exists and i3blocks_path.stat.islnk == False

- name: Register existing blocklet directory in ~/.config/i3blocks/blocklets
  stat:
    path: "{{ i3blocklets.dir }}"
  register: blocklets_path

- name: Backup existing blocklets directory
  command: mv "{{ i3blocklets.dir }}" "{{ i3blocklets.backup }}"
  when: blocklets_path.stat.exists and blocklets_path.stat.islnk == False

