---
- name: Install OpenJDK 8, 11, 13 and 14 via apt
  become: yes
  apt:
    pkg:
      - openjdk-8-jdk
      - openjdk-11-jdk
      - openjdk-13-jdk
      - openjdk-14-jdk
    state: latest
    update_cache: yes
    cache_valid_time: 3600
