---
- name: Install Network Manager OpenVPN via apt
  become: yes
  apt:
    pkg:
      - network-manager-openvpn
      - network-manager-openvpn-gnome
    state: latest
    update_cache: yes
    cache_valid_time: 3600
