---
- import_tasks: pacman.yaml
  when: ansible_facts['os_family']|lower == 'archlinux'

- name: Register existing config in ~/.config/rofi/config.rasi
  stat:
    path: "{{ rofi.file_path }}{{ rofi.file_name }}"
  register: config

- name: Create backup path for existing config
  file:
    path: "{{ rofi.backup_path }}"
    state: directory
  when: config.stat.exists and config.stat.islnk == False

- name: Backup esisting config files
  command: mv "{{ rofi.file_path }}{{ rofi.file_name }}" "{{ rofi.backup_path }}"
  when: config.stat.exists and config.stat.islnk == False

- name: Create config path
  file:
    path: "{{ rofi.file_path }}"
    state: directory

- name: Link config files
  file:
    src: "{{ rofi.repo_path }}{{ rofi.file_name }}"
    dest: "{{ rofi.file_path }}{{ rofi.file_name }}"
    state: link
