---
- name: Install dependencies via pacman
  become: yes
  community.general.pacman:
    name:
      - fuse2
      - glu
      - gstreamer
      - gtk2
      - lib32-libpng12
      - libpng12
      - ocl-icd
      - openssl-1.0
      - qt5-base
      - qt5-svg
      - qt5-webengine
      - qt5-webkit
      - qt5-websockets
      - libarchive
      - xdg-user-dirs
    state: present

- name: Clone/update AUR for DaVincy Resolve
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/davinci-resolve.git"
    dest: "{{ aur.davinci }}"

- name: Build DaVinci Resolve  package
  ansible.builtin.command: makepkg -f
  args:
    chdir: "{{ aur.davinci }}"

- name: Install DaVincyResolve package using pacman
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_fileglob:
    - "{{ aur.davinci }}/*.zst"
