---
- name: Install dependencies for discord via apt
  become: yes
  apt:
    pkg:
      - libatomic1
      - libgconf-2-4
      - libc++1
      - gconf2-common
      - libc++abi1
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Download discord from dircord.com to .dot/tmp/discord.deb
  get_url:
    url: https://discord.com/api/download?platform=linux&format=deb
    dest: "{{ ansible_env.PWD }}/tmp/discord.deb"

- name: Install /tmp/discrod.deb via apt
  become: yes
  apt:
    deb: "{{ ansible_env.PWD }}/tmp/discord.deb"
