---
- name: Register existing config in ~/.conf/tmux/tmux.conf
  stat:
    path: "{{ tmux.file_path }}{{ tmux.file_name }}"
  register: tmux_file

- name: Create backup path for existing config in ./backup/config/tmux
  file:
    path: "{{ tmux.backup_path }}"
    state: directory
  when: tmux_file.stat.exists and tmux_file.stat.islnk == False

- name: Backup existing ~/.conf/tmux/tmux.conf to ./backup/config/tmux/tmux.conf
  command: mv "{{ tmux.file_path }}{{ tmux.file_name }}" "{{ tmux.backup_path }}"
  when: tmux_file.stat.exists and tmux_file.stat.islnk == False

- name: Create config path
  file:
    path: "{{ tmux.file_path }}"
    state: directory

- name: Link config files
  file:
    src: "{{ tmux.repo_path }}{{ tmux.file_name }}"
    dest: "{{ tmux.file_path }}{{ tmux.file_name }}"
    state: link
