---
- name: Install tmux
  import_tasks: apt.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Link dot/tmux.conf to ~/.tmux.conf
  file:
    src: "{{ansible_env.PWD}}/tmux.conf"
    dest: "{{ansible_env.HOME}}/.tmux.conf"
    state: link


