---
- name: Install docker and docker-compose via apt
  become: yes
  apt:
    pkg:
      - docker.io
      - docker-compose
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Enable docker server
  become: yes
  shell: systemctl enable --now docker
