---
- name: Install Docker + dry
  import_tasks: apt.yaml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Add current user to docker group
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes

- name: Download install script for dry
  get_url:
    url: https://moncho.github.io/dry/dryup.sh
    dest: "{{ dry.scriptpath }}"
    mode: '0755'

- name: Run install script for dry
  become: yes
  shell: "{{ dry.scriptpath }}"

- name: Remove install script
  file:
    path: "{{ dry.scriptpath }}"
    state: absent

- name: Make dry executable
  become: yes
  file:
    path: /usr/local/bin/dry
    mode: '0755'
