---
- name: Install docker and docker-compose via pacman
  become: yes
  community.general.pacman:
    name:
      - docker
      - docker-compose
    state: latest
    update_cache: yes

- name: Enable docker server
  become: yes
  shell: systemctl enable --now docker
