---
- name: Install vim
  import_tasks: apt.yaml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Create directories in ~/tmp/vim/*
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ vim_dirs }}"

- name: Backup existing dotfiles from to dot/backup/
  command: mv "{{item.0}}" "{{item.1}}" creates="{{item.1}}" removes="{{item.0}}"
  loop: "{{ dest_files | zip(backup_files) | list }}"

- name: Link dotfile from dot/ to ~
  file:
    src: "{{item.0}}"
    dest: "{{item.1}}"
    state: link
  loop: "{{ src_files | zip(dest_files) | list}}"

